using System;
using System.IO;
using System.Text;
using PstBuilder.Eml;
using PstBuilder.Foundation;
using PstBuilder.Messaging;

// Emits a minimal Unicode PST. Demonstrates both a hand-built message (with an HTML body) and a
// message ingested from raw RFC822/MIME (.eml).
// Usage: dotnet run --project samples/PstBuilder.Sample [output.pst]

string outputPath = args.Length > 0 ? args[0] : "milestone.pst";

var store = new StoreWriter { StoreDisplayName = "PstBuilder Sample" };
var folder = store.IpmSubtree.AddFolder("Test Folder");

// 1) Hand-built message with an HTML body so it renders in viewers that prefer rich content.
var message = new MessageItem
{
    Subject = "Hello from PST Builder",
    Body = "This is a plain-text test message generated by PST Builder.\r\n",
    BodyHtml = "<html><body><p>This is a <b>test message</b> generated by " +
               "<span style=\"color:#0a7\">PST Builder</span>.</p>" +
               "<p>If you can read this, the HTML body works.</p></body></html>",
    DisplayTo = "Test User",
    SenderName = "PST Builder",
    SenderEmail = "noreply@pstbuilder.local",
};
message.Recipients.Add(new RecipientItem { DisplayName = "Test User", EmailAddress = "test@example.com" });
message.Attachments.Add(new AttachmentItem
{
    FileName = "readme.txt",
    MimeType = "text/plain",
    Content = Encoding.UTF8.GetBytes("This is an attached text file produced by PstBuilder.\r\n"),
});
folder.AddMessage(message);

// 2) Message ingested from raw .eml (the real source-adapter path).
string eml =
    "From: Alice Example <alice@example.com>\r\n" +
    "To: Test User <test@example.com>\r\n" +
    "Subject: Imported from EML\r\n" +
    "Date: Tue, 23 Jun 2026 14:05:00 +0000\r\n" +
    "MIME-Version: 1.0\r\n" +
    "Content-Type: text/html; charset=utf-8\r\n\r\n" +
    "<html><body><p>This message was parsed from raw MIME by the EML adapter.</p></body></html>\r\n";
folder.AddEml(Encoding.ASCII.GetBytes(eml));

// 3) A bulk folder to exercise large-folder support (multi-block HN, row-matrix subnode,
//    multi-AMap regions, and a multi-level Row ID BTH well past the old ~447-row limit).
const int bulkCount = 1000;
var bulk = store.IpmSubtree.AddFolder($"Bulk ({bulkCount} messages)");
for (int i = 1; i <= bulkCount; i++)
{
    var m = new MessageItem
    {
        Subject = $"Bulk message #{i:D3} - testing large folders with many rows",
        SenderName = $"Sender {i:D3}",
        DisplayTo = "Test User",
        Body = $"This is bulk message number {i}.",
        DeliveryTimeUtc = DateTime.UtcNow.AddMinutes(-i),
    };
    m.Recipients.Add(new RecipientItem { DisplayName = "Test User", EmailAddress = "test@example.com" });
    bulk.AddMessage(m);
}

// 4) Non-mail item types (exercise the named-property map).
var contacts = store.IpmSubtree.AddFolder("Contacts");
contacts.ContainerClass = "IPF.Contact";
contacts.AddContact(new ContactItem
{
    DisplayName = "Jane Doe", GivenName = "Jane", Surname = "Doe",
    Company = "Acme Corp", JobTitle = "Engineer",
    Email = "jane.doe@example.com", BusinessPhone = "+1 555 0100", Notes = "Met at conference.",
});

var calendar = store.IpmSubtree.AddFolder("Calendar");
calendar.ContainerClass = "IPF.Appointment";
calendar.AddAppointment(new AppointmentItem
{
    Subject = "Project sync", Location = "Conference Room A", Body = "Weekly status.",
    StartUtc = DateTime.UtcNow.Date.AddDays(1).AddHours(15),
    EndUtc = DateTime.UtcNow.Date.AddDays(1).AddHours(16),
});

var tasks = store.IpmSubtree.AddFolder("Tasks");
tasks.ContainerClass = "IPF.Task";
tasks.AddTask(new TaskItem { Subject = "Finish PST exporter", PercentComplete = 0.75, Status = 1, DueUtc = DateTime.UtcNow.AddDays(3) });

var notes = store.IpmSubtree.AddFolder("Notes");
notes.ContainerClass = "IPF.StickyNote";
notes.AddNote(new NoteItem { Subject = "Idea", Body = "Add OST support next.", Color = 1 });

// This sample drives StoreWriter directly so it can print header details below. For a one-liner,
// the same in-memory compose-and-write is available as Pst.Write(path, top => { ... }).
using (var fs = new FileStream(outputPath, FileMode.Create, FileAccess.ReadWrite))
using (var os = new PstOutputStream(fs, leaveOpen: true))
{
    var header = store.Write(os);
    Console.WriteLine($"Wrote {outputPath}");
    Console.WriteLine($"  File size:  {header.IbFileEof:N0} bytes");
    Console.WriteLine($"  NBT root:   {header.BrefNbt}");
    Console.WriteLine($"  BBT root:   {header.BrefBbt}");
}
