using System;
using System.Collections.Generic;
using System.IO;
using System.IO.Compression;
using System.Text;

    /// <summary>
    /// In plain words: makes small-but-real files (a PDF, a spreadsheet, a zip…) so the sample's
    /// attachments actually OPEN in a viewer, instead of the random bytes we used before (which listed
    /// correctly but failed to open). Everything is generated deterministically from code — no captured
    /// third-party binaries — so the sample stays MIT-clean. Each file is padded up to roughly the
    /// requested size so the export still reaches its target volume.
    /// </summary>
    internal static class SampleAttachments
    {
        public static byte[] Create(string fileName, int targetSize, int seq)
        {
            string ext = Path.GetExtension(fileName).ToLowerInvariant();
            string title = Path.GetFileNameWithoutExtension(fileName);
            switch (ext)
            {
                case ".pdf":  return Pdf(title, seq, targetSize);
                case ".csv":  return Csv(seq, targetSize);
                case ".docx": return Docx(title, seq, targetSize);
                case ".xlsx": return Xlsx(title, seq, targetSize);
                case ".zip":  return Zip(title, seq, targetSize);
                default:      return Txt(title, seq, targetSize);
            }
        }

        // ---- plain text / csv -------------------------------------------------------------------

        private static byte[] Txt(string title, int seq, int targetSize)
        {
            var sb = new StringBuilder($"{title}\r\nSample attachment #{seq} generated by PST Builder.\r\n\r\n");
            int i = 0;
            while (sb.Length < targetSize)
                sb.Append($"Line {i++:D6}: The quick brown fox jumps over the lazy dog. 0123456789.\r\n");
            return Encoding.ASCII.GetBytes(sb.ToString());
        }

        private static byte[] Csv(int seq, int targetSize)
        {
            var rnd = new Random(seq);
            var sb = new StringBuilder("Id,Date,Category,Description,Amount\r\n");
            int i = 0;
            while (sb.Length < targetSize)
                sb.Append($"{++i},2026-{(i % 12) + 1:D2}-{(i % 28) + 1:D2},Cat{i % 7},Line item number {i},{rnd.Next(100, 99999)}.{rnd.Next(0, 99):D2}\r\n");
            return Encoding.ASCII.GetBytes(sb.ToString());
        }

        // ---- PDF (hand-built, valid xref) -------------------------------------------------------

        private static byte[] Pdf(string title, int seq, int targetSize)
        {
            var content = new StringBuilder();
            content.Append("BT /F1 18 Tf 72 720 Td (").Append(PdfEscape($"{title}  (sample attachment #{seq})")).Append(") Tj ET\n");
            content.Append("BT /F1 12 Tf 72 690 Td (").Append(PdfEscape("Generated by PST Builder - deterministic sample content.")).Append(") Tj ET\n");
            // Pad the content stream with PDF comments (a '%' runs to end of line) to reach ~targetSize.
            while (content.Length < targetSize - 512)
                content.Append("% padding 0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF\n");
            byte[] cs = Encoding.ASCII.GetBytes(content.ToString());

            var objs = new List<byte[]>
            {
                Ascii("<</Type/Catalog/Pages 2 0 R>>"),
                Ascii("<</Type/Pages/Kids[3 0 R]/Count 1>>"),
                Ascii("<</Type/Page/Parent 2 0 R/MediaBox[0 0 612 792]/Resources<</Font<</F1 5 0 R>>>>/Contents 4 0 R>>"),
                Concat(Ascii($"<</Length {cs.Length}>>\nstream\n"), cs, Ascii("\nendstream")),
                Ascii("<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>"),
            };

            var ms = new MemoryStream();
            void W(string s) { var b = Encoding.ASCII.GetBytes(s); ms.Write(b, 0, b.Length); }
            W("%PDF-1.4\n");
            var offsets = new long[objs.Count + 1];
            for (int i = 0; i < objs.Count; i++)
            {
                offsets[i + 1] = ms.Length;
                W($"{i + 1} 0 obj\n");
                ms.Write(objs[i], 0, objs[i].Length);
                W("\nendobj\n");
            }
            long xref = ms.Length;
            W($"xref\n0 {objs.Count + 1}\n");
            W("0000000000 65535 f \n");                       // 20-byte free entry
            for (int i = 1; i <= objs.Count; i++) W($"{offsets[i]:D10} 00000 n \n"); // 20-byte in-use entries
            W($"trailer\n<</Size {objs.Count + 1}/Root 1 0 R>>\nstartxref\n{xref}\n%%EOF");
            return ms.ToArray();
        }

        private static string PdfEscape(string s) =>
            s.Replace("\\", "\\\\").Replace("(", "\\(").Replace(")", "\\)");

        // ---- OOXML (docx / xlsx) and plain zip --------------------------------------------------

        private static byte[] Docx(string title, int seq, int targetSize)
        {
            const string wns = "http://schemas.openxmlformats.org/wordprocessingml/2006/main";
            string doc =
                "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>" +
                $"<w:document xmlns:w=\"{wns}\"><w:body>" +
                $"<w:p><w:r><w:t xml:space=\"preserve\">{Xml($"{title} (sample #{seq})")}</w:t></w:r></w:p>" +
                "<w:p><w:r><w:t xml:space=\"preserve\">Generated by PST Builder.</w:t></w:r></w:p>" +
                "<w:sectPr><w:pgSz w:w=\"12240\" w:h=\"15840\"/></w:sectPr></w:body></w:document>";
            var parts = new Dictionary<string, byte[]>
            {
                ["[Content_Types].xml"] = Ascii(
                    "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>" +
                    "<Types xmlns=\"http://schemas.openxmlformats.org/package/2006/content-types\">" +
                    "<Default Extension=\"rels\" ContentType=\"application/vnd.openxmlformats-package.relationships+xml\"/>" +
                    "<Default Extension=\"xml\" ContentType=\"application/xml\"/>" +
                    "<Default Extension=\"bin\" ContentType=\"application/octet-stream\"/>" +
                    "<Override PartName=\"/word/document.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml\"/>" +
                    "</Types>"),
                ["_rels/.rels"] = Ascii(Rels("rId1",
                    "http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument", "word/document.xml")),
                ["word/document.xml"] = Encoding.UTF8.GetBytes(doc),
            };
            return BuildZip(parts, targetSize, "word/media/pad.bin");
        }

        private static byte[] Xlsx(string title, int seq, int targetSize)
        {
            const string sns = "http://schemas.openxmlformats.org/spreadsheetml/2006/main";
            const string rns = "http://schemas.openxmlformats.org/officeDocument/2006/relationships";
            string workbook =
                "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>" +
                $"<workbook xmlns=\"{sns}\" xmlns:r=\"{rns}\"><sheets>" +
                "<sheet name=\"Sheet1\" sheetId=\"1\" r:id=\"rId1\"/></sheets></workbook>";
            string sheet =
                "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>" +
                $"<worksheet xmlns=\"{sns}\"><sheetData>" +
                $"<row r=\"1\"><c r=\"A1\" t=\"inlineStr\"><is><t>{Xml($"{title} (sample #{seq})")}</t></is></c></row>" +
                "<row r=\"2\"><c r=\"A2\" t=\"inlineStr\"><is><t>Generated by PST Builder.</t></is></c></row>" +
                "</sheetData></worksheet>";
            var parts = new Dictionary<string, byte[]>
            {
                ["[Content_Types].xml"] = Ascii(
                    "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>" +
                    "<Types xmlns=\"http://schemas.openxmlformats.org/package/2006/content-types\">" +
                    "<Default Extension=\"rels\" ContentType=\"application/vnd.openxmlformats-package.relationships+xml\"/>" +
                    "<Default Extension=\"xml\" ContentType=\"application/xml\"/>" +
                    "<Default Extension=\"bin\" ContentType=\"application/octet-stream\"/>" +
                    "<Override PartName=\"/xl/workbook.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml\"/>" +
                    "<Override PartName=\"/xl/worksheets/sheet1.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml\"/>" +
                    "</Types>"),
                ["_rels/.rels"] = Ascii(Rels("rId1",
                    "http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument", "xl/workbook.xml")),
                ["xl/workbook.xml"] = Encoding.UTF8.GetBytes(workbook),
                ["xl/_rels/workbook.xml.rels"] = Ascii(Rels("rId1",
                    "http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet", "worksheets/sheet1.xml")),
                ["xl/worksheets/sheet1.xml"] = Encoding.UTF8.GetBytes(sheet),
            };
            return BuildZip(parts, targetSize, "xl/pad.bin");
        }

        private static byte[] Zip(string title, int seq, int targetSize)
        {
            var parts = new Dictionary<string, byte[]>
            {
                ["README.txt"] = Encoding.UTF8.GetBytes($"Onboarding pack: {title}\r\nSample #{seq}\r\nGenerated by PST Builder.\r\n"),
                ["docs/notes.txt"] = Txt(title, seq, 4000),
            };
            return BuildZip(parts, targetSize, "docs/filler.bin");
        }

        // Builds a ZIP (also the OPC container for docx/xlsx). Real parts are deflated; a final STORED
        // padding part (declared as .bin/octet-stream in the content types) brings the file to ~padTo.
        private static byte[] BuildZip(Dictionary<string, byte[]> parts, int padTo, string padName)
        {
            int realBytes = 0;
            foreach (var kv in parts) realBytes += kv.Value.Length + kv.Key.Length + 64; // rough overhead
            int padLen = Math.Max(0, padTo - realBytes - 256);

            var ms = new MemoryStream();
            using (var zip = new ZipArchive(ms, ZipArchiveMode.Create, leaveOpen: true))
            {
                foreach (var kv in parts)
                {
                    var e = zip.CreateEntry(kv.Key, CompressionLevel.Optimal);
                    using var s = e.Open();
                    s.Write(kv.Value, 0, kv.Value.Length);
                }
                if (padLen > 0)
                {
                    var e = zip.CreateEntry(padName, CompressionLevel.NoCompression);
                    using var s = e.Open();
                    var buf = new byte[8192];
                    for (int off = 0; off < padLen; off += buf.Length)
                        s.Write(buf, 0, Math.Min(buf.Length, padLen - off));
                }
            }
            return ms.ToArray();
        }

        // ---- helpers ----------------------------------------------------------------------------

        private static string Rels(string id, string type, string target) =>
            "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>" +
            "<Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\">" +
            $"<Relationship Id=\"{id}\" Type=\"{type}\" Target=\"{target}\"/></Relationships>";

        private static string Xml(string s) =>
            s.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;").Replace("\"", "&quot;");

        private static byte[] Ascii(string s) => Encoding.ASCII.GetBytes(s);

        private static byte[] Concat(params byte[][] parts)
        {
            int n = 0; foreach (var p in parts) n += p.Length;
            var r = new byte[n]; int o = 0;
            foreach (var p in parts) { Array.Copy(p, 0, r, o, p.Length); o += p.Length; }
            return r;
        }
    }
